// End to end with the local slicer container: open a model, Slice, preview, save.
import { chromium } from 'playwright-core';
import { BASE, BENCHY, CHROME, OUT, ensureMushroom } from './lib.mjs';
import { readFileSync } from 'node:fs';
const base = (process.argv[2] || BASE) + '?debug';
const browser = await chromium.launch({ executablePath: CHROME, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await browser.newContext({ viewport: { width: 1366, height: 768 }, acceptDownloads: true });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error' && !/cloudflareinsights/.test(m.text())) errors.push(m.text()); });
const check = (name, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); console.log(`${ok ? 'PASS' : 'FAIL'} ${name}: ${JSON.stringify(got)}${ok ? '' : ` (want ${JSON.stringify(want)})`}`); if (!ok) process.exitCode = 1; };
await page.goto(base);
await page.waitForTimeout(400);
await page.click('#sample');
await page.fill('.name-field input', 'Jordan');
const t0 = Date.now();
await page.click('#action button.primary');
await page.waitForSelector('#previewCard:not([hidden])', { timeout: 120000 });
console.log(`  (sliced and previewed in ${((Date.now() - t0) / 1000).toFixed(1)} s)`);
check('in preview', await page.evaluate(() => document.body.dataset.stage), 'preview');
const layers = await page.evaluate(() => window.umm.viewer.preview.layers.length);
check('about 40 mm / 0.18 mm layers', layers > 200 && layers < 230, true);
check('support lines present', await page.evaluate(() => window.umm.viewer.preview.types[4].segments.length > 0), true);
check('result card', await page.$eval('#action .result strong', (e) => e.textContent), '✓ Ready for the SD card');
console.log('  summary:', await page.$eval('#action .result p', (e) => e.textContent));
await page.screenshot({ path: OUT + '19-e2e-preview.png' });
const [download] = await Promise.all([page.waitForEvent('download'), page.click('#action button.primary')]);
check('file name', download.suggestedFilename(), 'jordan-support-test.gcode');
const path = await download.path();
const text = readFileSync(path, 'utf8');
check('starts with Cura header', text.startsWith(';FLAVOR:Marlin'), true);
check('school start block (G26 probe-fail clear)', /^G26\s+; clear potential 'probe fail' condition/m.test(text), true);
check('waits for 205 °C before the first layer', /^M109 R205\s+; wait for extruder to reach printing temp/m.test(text), true);
check('summary has no garbled characters', !/Â/.test(await page.$eval('#action .result p', (e) => e.textContent)), true);
console.log(errors.join('\n') || 'no errors');
await browser.close();
