import { chromium } from 'playwright-core';
import { BASE, BENCHY, CHROME, OUT, ensureMushroom } from './lib.mjs';
const base = (process.argv[2] || BASE) + '?debug';
const browser = await chromium.launch({ executablePath: CHROME, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error' && !/501|cloudflareinsights/.test(m.text())) errors.push(m.text()); });
const check = (name, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); console.log(`${ok ? 'PASS' : 'FAIL'} ${name}: ${JSON.stringify(got)}${ok ? '' : ` (want ${JSON.stringify(want)})`}`); if (!ok) process.exitCode = 1; };
await page.goto(base);
await page.waitForTimeout(400);
check('preview tab disabled at start', await page.$eval('.stage[data-stage=preview]', (b) => b.disabled), true);
await page.click('#sample');
const t0 = Date.now();
await page.setInputFiles('#fileInput', BENCHY);
await page.waitForSelector('#previewCard:not([hidden])', { timeout: 60000 });
console.log(`  (benchy opened in ${Date.now() - t0} ms)`);
check('stage is preview', await page.evaluate(() => document.body.dataset.stage), 'preview');
check('settings hidden', await page.$eval('#settings', (e) => e.hidden), true);
check('stats', await page.$$eval('.stats dd', (d) => d.map((x) => x.textContent)), ["3 h 10 min (Cura's guess)", '2.76 m · about 21 g', '266 · 0.18 mm each']);
check('top layer label', await page.$eval('#layerLabel', (e) => e.textContent), 'Layer 266 of 266 · 48.05 mm');
check('legend items', await page.$$eval('.legend-item', (x) => x.map((e) => e.textContent)), ['Outer wall', 'Inner walls', 'Top / bottom', 'Infill', 'Supports', 'Skirt / brim']);
check('models hidden', await page.evaluate(() => window.umm.viewer.models.every((m) => !m.mesh.visible)), true);
check('tools hidden', await page.$eval('.tools', (e) => getComputedStyle(e).display), 'none');
await page.screenshot({ path: OUT + '17-preview-top.png' });
// step down with keys and slider
await page.keyboard.press('Shift+ArrowDown');
check('shift+down = 10 layers', await page.$eval('#layerLabel', (e) => e.textContent), 'Layer 256 of 266 · 46.25 mm');
await page.$eval('#layerSlider', (s) => { s.value = '60'; s.dispatchEvent(new Event('input', { bubbles: true })); });
check('slider to layer 61', await page.$eval('#layerLabel', (e) => e.textContent), 'Layer 61 of 266 · 11.15 mm');
await page.click('.legend-item:has-text("Supports") input');
check('supports hidden', await page.evaluate(() => window.umm.viewer.previewParts[4].lines.visible), false);
await page.click('.legend-item:has-text("Supports") input');
await page.screenshot({ path: OUT + '18-preview-layer61.png' });
await page.keyboard.press('Home');
check('home = layer 1', await page.$eval('#layerLabel', (e) => e.textContent), 'Layer 1 of 266 · 0.35 mm');
check('action says file preview', await page.$eval('#action .action-empty', (e) => e.textContent), 'Previewing benchy_school_cura_4.13.2.gcode from this computer. It is not changed.');
// back to prepare
await page.keyboard.press('Escape');
check('back to prepare', await page.evaluate(() => document.body.dataset.stage), 'prepare');
check('models visible again', await page.evaluate(() => window.umm.viewer.models.every((m) => m.mesh.visible)), true);
check('settings back', await page.$eval('#settings', (e) => e.hidden), false);
check('preview tab now enabled', await page.$eval('.stage[data-stage=preview]', (b) => b.disabled), false);
await page.click('.stage[data-stage=preview]');
check('tab returns to preview', await page.evaluate(() => document.body.dataset.stage), 'preview');
console.log(errors.join('\n') || 'no errors');
await browser.close();
